### ISSUE TITLE
update CONTRIBUTING.md and README.md to point to Github for issues instead of Jira

### ISSUE THREAD

**Issue by NicolasMassart** [PegaSysEng/web3js-eea#103]
Now that we are back to using GIthub issues, replace references to Jira by this github repos issues link.

**Comment by macfarla** [comment]
I also noticed when I go here ->
https://pegasyseng.github.io/web3js-eea/latest/
it links to here ->
https://pegasyseng.github.io/web3js-eea/latest/CONTRIBUTING.md
which gives 404

**Comment by NicolasMassart** [comment]
> I also noticed when I go here ->
> https://pegasyseng.github.io/web3js-eea/latest/
> it links to here ->
> https://pegasyseng.github.io/web3js-eea/latest/CONTRIBUTING.md
> which gives 404

Yes because the readme is used to generate this doc home page, so here the link is relative and works on github but of course doesn't work on github. It would require to put the full link (domain + path) in the README.md
