### ISSUE TITLE
Release web3js-eea 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/web3js-eea#125]
Release (0.10.0) web3js-eea now https://github.com/PegaSysEng/web3js-eea/pull/122 has been merged so the latest version of web3js-eea will work with the latest release of Besu. 

- [x] Release web3js-eea 
- [x] Ensure web3js-eea reference doc is tagged and pointed to the latest version 
- [x] Update Besu changelog to remove point about web3js-eea not working with latest version of Besu

**Comment by macfarla** [comment]
Is there anything special to do for point 2 @MadelineMurray ? Besu docs just points to latest https://pegasyseng.github.io/web3js-eea/latest/ and I can't see that github pages is versioned?

**Comment by macfarla** [comment]
https://www.npmjs.com/package/web3-eea/v/0.10.0
https://github.com/PegaSysEng/web3js-eea/releases/tag/v0.10.0

**Comment by macfarla** [comment]
Do we need to update the changelog? There's a note against Besu 1.5.3 saying it doesn't work with web3js-eea 0.9.0 which is still valid

**Comment by MadelineMurray** [comment]
Changelog is updated.
