### ISSUE TITLE
Timeout message in "getTransactionReceipt" function

### ISSUE THREAD

**Issue by gbarcomu** [PegaSysEng/web3js-eea#17]
When obtaining a transaction receipt from eth, if the receipt is not found it is thrown the following error:
`throw Error("Waiting for tx to be mined");`
However, if the last attempt fails, the same error is thrown to the caller function.

It would be nice to have more information about it.

E.g. ( line 59, index.js:
`return reject('No tx found, timeout');`

**Comment by ekellstrand** [comment]
Moving to Jira at https://pegasys1.atlassian.net/browse/PAN-2774
